#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const DATA_DIR = path.join(process.cwd(), 'data');
const trackerPath = path.join(DATA_DIR, 'tracker.json');
const dailyPath = path.join(DATA_DIR, 'daily-results.json');
const modelPath = path.join(DATA_DIR, 'model-data.json');
function readJson(p, fallback){ try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; } }
function writeJson(p, data){ fs.mkdirSync(path.dirname(p), {recursive:true}); fs.writeFileSync(p, JSON.stringify(data, null, 2) + '\n'); }
function todayCT(){ return new Intl.DateTimeFormat('en-CA', { timeZone:'America/Chicago', year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date()); }
const now = new Date().toISOString();
const tracker = readJson(trackerPath, { version:4, generatedAt:null, picks:[], market:{drp:[], kprop:[]}, players:{}, teams:{}, days:{}, dailyResults:[], debug:{} });
tracker.version = 4;
tracker.picks ||= [];
tracker.market ||= { drp: [], kprop: [] };
tracker.market.drp ||= [];
tracker.market.kprop ||= [];
tracker.players ||= {};
tracker.teams ||= {};
tracker.days ||= {};
tracker.dailyResults ||= [];
tracker.debug ||= {};
tracker.generatedAt = now;
tracker.debug.lastGithubActionRun = now;
tracker.debug.repoSync = true;
tracker.debug.repoSyncNote = 'Repo-side scheduled sync. Browser auto-downloads are disabled; all committed JSON files are the source of truth across devices.';
tracker.debug.currentDateCT = todayCT();
writeJson(trackerPath, tracker);
const daily = readJson(dailyPath, { version:1, results:[] });
daily.version ||= 1;
daily.results ||= [];
daily.lastCheckedAt = now;
daily.currentDateCT = todayCT();
writeJson(dailyPath, daily);
const model = readJson(modelPath, { version:1, generatedAt:null, teams:{}, players:{}, notes:[] });
model.version ||= 1;
model.generatedAt = now;
model.notes ||= [];
model.notes = [
  'Generated by GitHub Actions repo data sync.',
  'Lineup data feeds HR Projections and Pitcher Report when data/lineups.json is present.'
];
writeJson(modelPath, model);
console.log(`Repo tracker sync complete: ${tracker.picks.length} HR picks, ${tracker.market.drp.length} DRP picks, ${tracker.market.kprop.length} K props.`);
