#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const DATA_DIR = path.join(process.cwd(), 'data');
const trackerPath = path.join(DATA_DIR, 'tracker.json');
const dailyPath = path.join(DATA_DIR, 'daily-results.json');
const modelPath = path.join(DATA_DIR, 'model-data.json');
function readJson(p, fallback){ try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; } }
function writeJson(p, data){ fs.mkdirSync(path.dirname(p), {recursive:true}); fs.writeFileSync(p, JSON.stringify(data, null, 2) + '\n'); }
function todayCT(){ return new Intl.DateTimeFormat('en-CA', { timeZone:'America/Chicago', year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date()); }
const now = new Date().toISOString();
function summary(obj){
  const wins = Number(obj?.wins ?? obj?.correct ?? 0) || 0;
  const losses = Number(obj?.losses ?? obj?.incorrect ?? Math.max((Number(obj?.total || 0) || 0) - wins, 0)) || 0;
  const total = Number(obj?.total || (wins + losses)) || (wins + losses);
  return { wins, losses, total };
}
function preserveOrGrow(existing, wins, total){
  const old = summary(existing);
  const next = { wins, losses: Math.max(total - wins, 0), total };
  return next.total > old.total ? next : old;
}
function isWinLoss(r){ return r && (r.result === 'win' || r.result === 'loss'); }
const tracker = readJson(trackerPath, { version:4, generatedAt:null, picks:[], market:{drp:[], kprop:[]}, players:{}, teams:{}, days:{}, dailyResults:[], debug:{} });
tracker.version = 4;
tracker.picks ||= [];
tracker.market ||= { drp: [], kprop: [] };
tracker.market.drp ||= [];
tracker.market.kprop ||= [];
tracker.players ||= {};
tracker.teams ||= {};
tracker.days ||= {};
tracker.dailyResults ||= [];
tracker.allTime ||= {};
tracker.allTime.hr ||= { wins:0, losses:0, total:0 };
tracker.allTime.kprop ||= { wins:0, losses:0, total:0 };
tracker.allTime.drp ||= { wins:0, losses:0, total:0 };
tracker.debug ||= {};
tracker.generatedAt = now;
tracker.debug.lastGithubActionRun = now;
tracker.debug.repoSync = true;
tracker.debug.repoSyncNote = 'Repo-side scheduled sync. Browser auto-downloads are disabled; all committed JSON files are the source of truth across devices.';
tracker.debug.currentDateCT = todayCT();
const finalHr = tracker.picks.filter(p => p && p.final === true);
const finalHrWins = finalHr.filter(p => p.hit === true).length;
const finalK = tracker.market.kprop.filter(isWinLoss);
const finalKWins = finalK.filter(r => r.result === 'win').length;
const finalDrp = tracker.market.drp.filter(isWinLoss);
const finalDrpWins = finalDrp.filter(r => r.result === 'win').length;
tracker.allTime.hr = preserveOrGrow(tracker.allTime.hr, finalHrWins, finalHr.length);
tracker.allTime.kprop = preserveOrGrow(tracker.allTime.kprop, finalKWins, finalK.length);
tracker.allTime.drp = preserveOrGrow(tracker.allTime.drp, finalDrpWins, finalDrp.length);
tracker.debug.allTimeSummaryUpdatedAt = now;
writeJson(trackerPath, tracker);
const daily = readJson(dailyPath, { version:1, results:[] });
daily.version ||= 1;
daily.results ||= [];
daily.lastCheckedAt = now;
daily.currentDateCT = todayCT();
writeJson(dailyPath, daily);
const model = readJson(modelPath, { version:1, generatedAt:null, teams:{}, players:{}, notes:[] });
model.version ||= 1;
model.generatedAt = now;
model.notes ||= [];
model.notes = [
  'Generated by GitHub Actions repo data sync.',
  'Lineup data feeds HR Projections and Pitcher Report when data/lineups.json is present.'
];
writeJson(modelPath, model);
console.log(`Repo tracker sync complete: ${tracker.picks.length} HR picks, ${tracker.market.drp.length} DRP picks, ${tracker.market.kprop.length} K props.`);
